# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-04 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('total_no_of_tasks', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_img', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_ques', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('players', models.ManyToManyField(to='game.Player')),
                ('questions', models.ManyToManyField(to='game.Question')),
            ],
        ),
    ]
