# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20191104_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='qwertyui', max_length=10),
            preserve_default=False,
        ),
    ]
